### ISSUE TITLE
ActiveJob requires rails upgrade

### ISSUE THREAD

**Issue by trombonebiker** [ShowPanda/App#28]
Currently using Rails 4.1.8 however ActiveJob requires >= Rails 4.2.x. I've upgraded my rails gem to 4.2.5.1 so can use 4.1.8 as well as a version which supports ActiveJob. Try upgrading your rails gem to the same and if it works I'll try and upgrade the version of rails that the app uses.

In the terminal (windows) you'd type
$ gem install rails -v 4.2.5.1

and if it throws the error of not being able to connect to rubygems.org, try
$ gem install rails -v 4.2.5.1 -s http://rubygems.org

If/when you've done that then I'll see about upgrading the app's version of Rails.

**Comment by davidsmpsn** [comment]
I've done this now
