### ISSUE TITLE
Trophy pages links

### ISSUE THREAD

**Issue by davidsmpsn** [ShowPanda/App#29]
Is there a way of changing the url for the points based and firsts based trophy pages so they are under the subdirectory 'trophies'? Would make sidebar link highlighting for the current page a lot easier and it makes a bit more sense.

**Comment by trombonebiker** [comment]
It's possible although I'd have to put points-based and firsts-based trophies in the same model, which might become a problem when I have to separate them out from each other in order to calculate the winners... I'll see what I can do though
