### ISSUE TITLE
Clicking on a section opens the show view for that section

### ISSUE THREAD

**Issue by trombonebiker** [ShowPanda/App#9]
Currently need to manually type in the ID number for the relevant section, which isn't necessarily the same as the section number, also won't work when we run the browser in kiosk mode as the address bar won't be constantly displayed on-screen

**Comment by davidsmpsn** [comment]
Is this when creating a new section?

**Comment by trombonebiker** [comment]
No, in the index view when you click on the section row in the table it should open the show view for that section. Seems like you've fixed it.
